export const DEFAULT_VOICE = "Gwyneth";
export const VOICES = {
  Ivy: "Ivy [English - American]",
  Joanna: "Joanna [English - American]",
  Joey: "Joey [English - American]",
  Justin: "Justin [English - American]",
  Kendra: "Kendra [English - American]",
  Kimberly: "Kimberly [English - American]",
  Salli: "Salli [English - American]",
  Nicole: "Nicole [English - Australian]",
  Russell: "Russell [English - Australian]",
  Emma: "Emma [English - British]",
  Brian: "Brian [English - British]",
  Amy: "Amy [English - British]",
  Raveena: "Raveena [English - Indian]",
  Geraint: "Geraint [English - Welsh]",
  Ricardo: "Ricardo [Brazilian Portuguese]",
  Vitoria: "Vitoria [Brazilian Portuguese]",
  Lotte: "Lotte [Dutch]",
  Ruben: "Ruben [Dutch]",
  Mads: "Mads [Danish]",
  Mathieu: "Mathieu [French]",
  Celine: "Celine [French]",
  Chantal: "Chantal [Canadian French]",
  Marlene: "Marlene [German]",
  Dora: "Dora [Icelandic]",
  Karl: "Karl [Icelandic]",
  Carla: "Carla [Italian]",
  Giorgio: "Giorgio [Italian]",
  Mizuki: "Mizuki [Japanese]",
  Liv: "Liv [Norwegian]",
  Maja: "Maja [Polish]",
  Jan: "Jan [Polish]",
  Ewa: "Ewa [Polish]",
  Cristiano: "Cristiano [Portuquese]",
  Ines: "Ines [Portuquese]",
  Carmen: "Carmen [Romanian]",
  Maxim: "Maxim [Russian]",
  Tatyana: "Tatyana [Russian]",
  Enrique: "Enrique [Spanish]",
  Penelope: "Penelope [US Spanish]",
  Miguel: "Miguel [US Spanish]",
  Conchita: "Conchita [Castilian Spanish]",
  Astrid: "Astrid [Swedish]",
  Filiz: "Filiz [Turkish]",
  Gwyneth: "Gwyneth [Welsh]"
};
