import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menu = [
  // { title: "gobbledygook", link: `${process.env.PUBLIC_URL}/` },
  { title: "ProcGenConLang", link: `/procgenconlang` },
  { title: "Phrase book", link: `/phrase-book` },
  // { title: "About", link: `${process.env.PUBLIC_URL}/About` },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <footer>
          {menu.map((entry) => {
            return (
              <Link key={entry.link} href={entry.link}>
                {entry.title}
              </Link>
            );
          })}
          <span>
            made by <a href="https://twitter.com/feelic">@feelic</a> ;-){" "}
          </span>
        </footer>
      </body>
    </html>
  );
}
